### ISSUE TITLE
BIC field is difficult to use

### ISSUE THREAD

**Issue by simon-lgb** [JDAV-Bayern/fahrtkostenabrechnung#17]
The field only shows up once the user clicks out of the IBAN field, which makes it easy to miss. A simple solution would be to always display it.
If you go back and forward again, the field is hidden once again.
The BIC is actually not required for most SEPA countries, not just inside Germany.
The field is also the only one that does not get saved.

**Comment by josephhirsch** [comment]
What do you suggest? Removing it all together?

**Comment by simon-lgb** [comment]
I think a solution for the first two issues would be to update the visibility as the user is typing the IBAN and to update the state when the page is reopened.
Maybe it also makes sense to show the field by default and only hide or disable it when it becomes unnecessary.
The second two issues can be fixed easily I think.

We should also consider whether to clear the BIC if the IBAN is changed to a value that causes the field to be hidden.

**Comment by simon-lgb** [comment]
The BIC field was improved in 0fa33f1161aac6cfdf65209cb0c0873ed340e3b2
However, the field could still be hidden for more countries in the future. Also we could check if the BIC exists similiar to what we do for PLZ, however this is probably unnecessary.
