### ISSUE TITLE
Validation of Bavarian / non Bavarian reimbursements

### ISSUE THREAD

**Issue by josephhirsch** [JDAV-Bayern/fahrtkostenabrechnung#19]
This apparently does not depend on the address of the participant but on the Sektion. We need to discuss further requirements for this.

**Comment by simon-lgb** [comment]
One solution would be to also ask participants for their Sektion

**Comment by josephhirsch** [comment]
Bayern / Nicht Bayern machen wir anhand der Sektionszugehörigkeit
