### ISSUE TITLE
Improve usability of adding passengers for Car expenses

### ISSUE THREAD

**Issue by josephhirsch** [JDAV-Bayern/fahrtkostenabrechnung#20]
The LGS has the wish to add a properly "managed" list here, where passengers can be individually added and removed.

**Comment by simon-lgb** [comment]
Could we just ask for the total number of passengers?

**Comment by josephhirsch** [comment]
Wenn wir nur die Zahl abfragen, kann keine Validieren mehr von LGS Seite vorgenommen werden.
