### ISSUE TITLE
Reimbursement of plan expenses should always be 12.50

### ISSUE THREAD

**Issue by josephhirsch** [JDAV-Bayern/fahrtkostenabrechnung#21]
There is no need to distinguish the different plans, we will always reimburse 12.50€ apparently. Lets verify this again before implementation.

**Comment by simon-lgb** [comment]
According to the current paper form, this is how we handle it, but the reimbursement is 12,25 €

**Comment by josephhirsch** [comment]
Ja, es werden immer nur 12,50€ erstattet
