### ISSUE TITLE
Simplify discount card and car type fields?

### ISSUE THREAD

**Issue by simon-lgb** [JDAV-Bayern/fahrtkostenabrechnung#31]
Würde es reichen, die Art des Autos sowie die BahnCard nur einmal abzufragen? Das würde die Möglichkeiten zwar theoretisch einschränken, aber trotzdem alle für mich denkbaren Fälle abdecken. So ist es aktuell auch auf dem Papierformular.

**Comment by josephhirsch** [comment]
Hm, ich bin mir nicht sicher. Der Wert wird bei der nächsten Auslage aus jeder vorherigen übernommen. Und wenn wir es einmal zentral abfragen sollten wir aus usability gründen nur das abfragen, was auch wirklich gebraucht wird.

**Comment by simon-lgb** [comment]
Wir bleiben beim aktuellen Format.
