### ISSUE TITLE
PDF page break

### ISSUE THREAD

**Issue by simon-lgb** [JDAV-Bayern/fahrtkostenabrechnung#46]
Die Tabelle mit den Auslagen spaltet einzelne Zeilen über zwei Seiten. Das macht sie schwer lesbar.
Mögliche Lösung: https://www.npmjs.com/package/jspdf-autotable

**Comment by josephhirsch** [comment]
Ich würde das runter priorisieren, solange es noch gut lesbar ist. Perspektivisch wollen wir weg von einer Clientseitigen PDF Erzeugung.
