### ISSUE TITLE
FR: Daten Export/Import

### ISSUE THREAD

**Issue by felsgaertner** [JDAV-Bayern/fahrtkostenabrechnung#51]
Feature Request / User Story:

Ich als User möchte meine "Stammdaten", also 

* Abfahrtsort der Reise
* persönliche Daten ("Angaben zu Dir" mit Wohnort und Kontodaten)

exportieren können (z.B. als JSON oder XML), damit ich diese bei einer neuen Abrechnung wieder als lokalen Upload einfügen kann. Da das Abrechnungstool nur lokal im Browser arbeitet und keine Daten zentral speichert, würde das die Nutzung bei häufiger Anwendung erleichtern.

**Comment by josephhirsch** [comment]
Die Daten werden aktuell bereits im local storage gespeichert. (Außer Abfahrtsort, aber das sehe ich als nicht so gewinnbringend an, da schnelle eingabe). Einen echten benefit hätte es für mich, wenn die Daten Geräteübergreifend synchronisiert würden und dafür braucht es aus meiner Sicht einen Login und eine Benutzerkonto wie anderswo üblich. Ich sehe es als nicht realistisch, dass Leute eine json runterladen und diese dann verwalten oder gar auf andere gerate übertragen.
