### ISSUE TITLE
Inkonsistente Formatierung der PDF

### ISSUE THREAD

**Issue by simon-lgb** [JDAV-Bayern/fahrtkostenabrechnung#54]
Auf meinem Rechner (Windows 10, Firefox) sind die Leerräume zu gering. Auf Mac OS mit Firefox gibt es keine Probleme.

**Comment by josephhirsch** [comment]
Ich würde das runter priorisieren, solange es noch gut lesbar ist. Perspektivisch wollen wir weg von einer Clientseitigen PDF Erzeugung.
