### ISSUE TITLE
IBAN Feld besser lesbar machen

### ISSUE THREAD

**Issue by josephhirsch** [JDAV-Bayern/fahrtkostenabrechnung#63]
Bei der Eingabe der IBAN kann es mitunter angenehmer sein, die eingegebene IBAN in 4-er Blöcken zu lesen und validieren. Das input Feld könnte in der Darstellung also alle 4 Zeichen einen Abstand einfügen, ohne diesen in den Value zu übernehmen.

**Comment by simon-lgb** [comment]
Was zumindest aktuell schon möglich ist, ist die Eingabe von Leerzeichen (auch an beliebigen stellen, nicht nur alle 4 Zeichen)
